### ISSUE TITLE
False positive - forums.toucharcade.com

### ISSUE THREAD

**Issue by lnlyssg** [mitchellkrogza/Badd-Boyz-Hosts#33]
Not sure why this is included - it's the forums for iOS/Android gaming site https://toucharcade.com

**Comment by vaguerant** [comment]
I don't know if this is still the case, but TouchArcade's forums used to rewrite all outgoing links so they could be tracked by the site, and they did go via forums.toucharcade.com if I'm recalling correctly. I would assume this is why the forums were blocked in the first place.

**EDIT:** Also, sorry if I'm just not understanding how this repo works, but `forums.toucharcade.com` is still in the file `hosts` on this repo.

**Comment by funilrys** [comment]
Thanks for the clarification @vaguerant.

When we remove a domain, we remove it from here and we also add it to [CENTRAL-REPO.Dead.Inactive.Whitelisted.Domains.For.Hosts.Projects](https://github.com/mitchellkrogza/CENTRAL-REPO.Dead.Inactive.Whitelisted.Domains.For.Hosts.Projects). So that at each session of our [tests against dead-domain](https://travis-ci.org/mitchellkrogza/Badd-Boyz-Hosts)  - which works [PyFunceble](https://github.com/funilrys/PyFunceble) - we remove all whitelisted domain.
