### ISSUE TITLE
Correction

### ISSUE THREAD

**Issue by raspberrycoulis** [mitchellkrogza/Badd-Boyz-Hosts#35]
I’ve noticed you list the following websites as spam:

nibbler.silktide.com

And

silktide.com

I work at Silktide and I wanted to shed light on the company and what we do. 

Nibbler is a website testing tool (free) that many people use to check their websites. It does spider a website, but only if requested. It is not automatic and does not randomly spider websites. 

Silktide is our company name - the silktide.com domain is our company website. It is not a spam site nor does it do anything other than host our website and Nibbler on its own subdomain. 

As a PiHole user myself, I have whitelisted both to prevent issues with accessing our own website but I felt it was incorrectly blacklisted and opened this issue.

**Comment by funilrys** [comment]
Almost 95% of the domains listed here are flagged because they have been found probing one of our websites. 

So now that that point is clear, I'm going to review this whitelisting request but as the final decision comes from both of us I can not guarantee anything yet.

From a first look, everything looks legitimate but as said, @mitchellkrogza mind also count so you'll have to wait until next week (normally) as he is currently enjoying some time away from keyboards.

Thanks for submitting this issue.
Thanks in advance for your patience.

Have a nice day/night.

**Comment by raspberrycoulis** [comment]
That’s fine and makes sense. Nibbler is a website testing tool, to check for quality issues but as it has to spider and download a website to do this, people may misconstrue this as a bot up to no good.

I’ve manually whitelisted our domains but it would be a shame if others are blocked from our legitimate website.

Thanks for the speedy reply.

**Comment by mitchellkrogza** [comment]
@raspberrycoulis Thanks for reporting this, this made it in here from my original lists for my Bot Blocker projects for Badd Boyz however @funilrys they can both be safely removed.

**Comment by raspberrycoulis** [comment]
Great, thanks.
