### ISSUE TITLE
[FIXED] Russian blog service is mistakenly banned

### ISSUE THREAD

**Issue by sergeevabc** [mitchellkrogza/Badd-Boyz-Hosts#4]
Not so long ago [you were quick to exclude][1] major Russian social network ```ok.ru``` from your hosts file.

Not it comes to Russian blog platform Liveinternet, which is mentioned here twice as ```liveinternet.ru``` and ```www.liveinternet.ru```. It exists [since 2003][2], its creator [German Klimenko][3] is the Kremlin’s official Internet adviser [since January 2016][4]. Respectable reference to reconsider, isn’t it?

The only reason of current ban I could think of is that Liveinternet (Russian alternative to Livejournal), displays ads for free users, but uses dedicated sub domain ```ad.liveinternet.ru``` for that purpose (like even Youtube does), which I do not ask to remove.

[1]: https://github.com/StevenBlack/hosts/issues/276
[2]: https://ru.wikipedia.org/wiki/LiveInternet
[3]: https://ru.wikipedia.org/wiki/Клименко,_Герман_Сергеевич
[4]: http://www.en.kremlin.ru/events/president/news/51137

**Comment by mitchellkrogza** [comment]
Yes and IF YOU TOO THE TIME TO REFERENCE THE ISSUE ON ok.ru it was fixed within a few hours. If you BOTHER to read why it was on the list in the first place then you might just understand why I removed it so WHAT exactly is your problem dude???

**Comment by mitchellkrogza** [comment]
You seem to have a big problem with me being one person maintaining a log of bad referrers whereas almost all the other data sources are also at best maintained by one person, so please let me know what your problem is??? I've put more work into maintaining a clean list but do have remnants that exist from very old lists I started with and I am probably the quickest person to ever respond to removals.

**Comment by mitchellkrogza** [comment]
I will recheck through logs tomorrow regarding liveinternet.ru and remove once I confirm it. Quite simple to simply ask for something instead of accusing me of deliberately blocking valid networks.

**Comment by sergeevabc** [comment]
Nobody accused you of anything, stop being hysterical and behave decently as a civilized adult should.
Issue is reported politely and to the point to be processed in the same way, i.e. politely and to the point.

**Comment by mitchellkrogza** [comment]
Actually you started with the accusations, go read all issues on all my repos and see how patient I am with dealing professionally with issues in a professional manner ALWAYS even with people who go on and on and on about issues. It's Saturday night and I will deal with this in the morning. I spend more time keeping myself lists accurate than 90% of people out there. Not over reacting simply saying that you could simply report a false positive instead of accusing me of deliberately blocking ok.ru when i explained at the time it WAS a false positive and a mistake and it was remedied within 12 hours. No??

**Comment by sergeevabc** [comment]
Overusing CAPS and ??? clearly indicates how professional and patient you are — it is conniption.
Reason for that is your inclination to think beyond what is said and fight over imaginary threats.
For example, you believe you were accused of deliberately blocking any resources, which is not true:

- [issue][1] about ```ok.ru``` contains 3 lines: false positive alert, kind request to remove, gratitude.
- this issue about ```liveinternet.ru``` contains 3 paragraphs: mention of our previous meeting and false positive alert with arguments which could help you make a right decision.

What you are actually angry about is that I [dared to question the reliability][2] of your list while talking with another repo maintainer. Again, there was no accusation except telling facts: you are an individual who populates his list in a spare time, not [some security-dedicated enterprise][3], so be humble. 

[1]: https://github.com/StevenBlack/hosts/issues/276
[2]: https://github.com/StevenBlack/hosts/issues/281#issuecomment-296382576
[3]: https://safebrowsing.google.com/

**Comment by mitchellkrogza** [comment]
@sergeevabc Removed in https://github.com/mitchellkrogza/Badd-Boyz-Hosts/commit/c7ff2da0e7b474058602c55d87908ed7ac1b97ad 

I actually am very patient and professional and it seems we had a language and miscommunication problem last night. I am under a lot of stress with my dying father so apologies for lashing out at you due to miscommunications with what you were saying. 

Yes I am just and individual but I spend more than just spare time on my projects and my aim is to always keep them clean and accurate which is what I do. A lot of lists out there are also maintained by merely one person and a great deal of them contain hundreds of dead domains and false positives. It did feel that your comment on the other repo were directly aimed at me and I felt it unwarranted as I really do spend a great deal of my time on these projects.

**Comment by sergeevabc** [comment]
Thank you, @mitchellkrogza.

Sorry to hear about your father. In this regard, I recall Pierre-Auguste Renoir, the French painter who became disabled by the end of his life. His friend Matisse asked him why he persisted in painting at the expense of such torture. Renoir answered: “Pain passes but beauty remains”. Stay strong and keep on.

Maintaining hosts by yourself is not wrong per se. The one who deserves criticism is @StevenBlack, the hosts aggregator. He should question what makes any source reliable except for its author’s willingness to exclude false positives, i.e. how rigorous the process of collecting data is. Instead he [blindly asserts][1] that authors “study these things“, which is controversial. For example, a South African photographer like you is obviously limited to study non-English entities properly (Russian, Cherokee, Japanese, etc), yet Steven believes “it’s completely unwarranted” and yells “get lost”. Smarter aggregators such as @notracking leave room for reasonable doubt and populate dedicated whitelist that overrides [all other sources][2].

[1]: https://github.com/StevenBlack/hosts/issues/281#issuecomment-296381413
[2]: https://github.com/notracking/hosts-blocklists#public-lists-that-are-used-as-source

**Comment by mitchellkrogza** [comment]
No problem @sergeevabc and sorry for my outbursts, I am really going through a tough time.
I grep'd through a years worth of logs and did not find ANY wrong doing by liveinternet.ru which made me realize this was one of the remnants from the original list I started with when I started building my blocker. I did not even find one reference in a years worth of logs to even ad.liveinternet.ru so I consider it perfectly clean and hence as I did I removed it. 

It's difficult for @stevenblack to be able to verify all lists and it seems a lot of lists simply copy from others without checking. I have found liveinternet.ru on a number of blockers, all simply copied from each other without ever checking.

I started my original list as I said with a mere 200, everything else present in my list is taken from daily logs from 18+ web sites I operate and I check each and every website in a browser before I even add it to make sure they are actually a spam site and not perhaps someone linking to an article on my site thereby providing a valuable inbound link, so I am indeed very careful in additions to my list. I spend a good 2-3 hours each morning going through daily logs which gets emailed to me of my top referrers over the past 24 hours .... very time consuming, especially having to check through each and every one of them manually.

I can however 100% from a years worth of logs support removal of liveinternet.ru from and and all other blocker lists.
