### ISSUE TITLE
Unblock adf.ly

### ISSUE THREAD

**Issue by Extamov** [mitchellkrogza/Badd-Boyz-Hosts#40]
adf.ly is a url shortener, blocking it will break all shortnered adf.ly links.

**Comment by funilrys** [comment]
@ExtendLord, sorry but we are reversing this asap.

I think that https://github.com/StevenBlack/hosts/issues/607#issuecomment-387301955 is more than clear.

In the name of our team, I apologize for all issues caused by the reversion of the blocking of this domain but we share the same opinion as @kronflux (along with other opinions about adf.ly) in the previously mentioned linked link. 

**The `unblocking` of this domain was a mistake.**

For reference regarding past decision of our team around adf.ly:
- https://github.com/mitchellkrogza/Ultimate.Hosts.Blacklist/issues/103
