### ISSUE TITLE
Domain Removal: leifsex.com

### ISSUE THREAD

**Issue by derleif** [mitchellkrogza/Badd-Boyz-Hosts#57]
maybe was a bad site some years ago.
It's my own domain since 2016

**Comment by funilrys** [comment]
Immer ballern !? Echt !? Was soll ich damit verstehen :smile_cat: ?
Meine einzige Frage, wie können wir dich vertrauen ?

-------------------------
For the non german:

Always shoot! Really !? What do you mean by that?
My only question, how can we trust you?

-------------------------
Okay, more seriously can you add a TXT entry do your DNS so that I get the following ? This is a way to verify what you state. 

Also in the future, after verification, your domain will be in an internal list for regular checking FYI.  :smile_cat:  

```
$ dig +short TXT leifsex.com
# I should get the following output: "https://github.com/mitchellkrogza/Badd-Boyz-Hosts/issues/57"
```

Cheers,
Nissar

**Comment by derleif** [comment]
It's just an inside joke and a test system of mine ;)
Sure, just added the record.

Thanks,
Leif

**Comment by mitchellkrogza** [comment]
Well done @funilrys my friend, TXT records 👍🏻👍🏻👍🏻 now why didn't I think of that.

**Comment by funilrys** [comment]
Thanks @mitchellkrogza :smile_cat: :+1:
